### ISSUE TITLE
Update to 24.0.6

### ISSUE THREAD

**Issue by zekabra** [DesktopECHO/nextcloudpi#3]
How to update this version of Nextcloudpi for Android?

Currently there is a notification to upgrade to version 24.0.6.

It's safe to do or due to the modifications this version has to work on Android, is it not advisable to do?

**Comment by zekabra** [comment]
Answering to myself, I decided to take a chance and did the update, apparently everything went fine, I haven't detected any problems related to the update yet, which doesn't mean that they don't exist

**Comment by DesktopECHO** [comment]
Hi, yes it should be safe to update to new NC versions. 

The only thing to watch out for is disk space.   The minimum size needed for the image install is 4GB, but that is very tight.   

Setting an image larger than 4GB will allow updates to run much more smoothly.

**Comment by zekabra** [comment]
@DesktopECHO When installing the container I didn't choose image, but directory, is there any drawback for choosing this option? if I choose image, won't nextcloud be limited to the size I choose for the image and it would fill up quickly after uploading some files?

Thanks for all the work on these projects, I also use pi-hole, I am a fan of your work, the ideal would be to be able to run them all using the same container.

**Comment by DesktopECHO** [comment]
Try with an image to see if your reboot issue persists.  

Ideally you would add a mount in Linux Deploy so NextCloud could be stored on that instead.  Something like /var/www -> /data/local/www

**Comment by seanganteng** [comment]
> How to update this version of Nextcloudpi for Android?
> 
> Currently there is a notification to upgrade to version 24.0.6.
> 
> It's safe to do or due to the modifications this version has to work on Android, is it not advisable to do?

How do you upgrade it?
